version: 3.0.{build}

branches:
  only:
    - master

init:
  - git config --global core.autocrlf input

build_script:
  - cmd: build.cmd

test: off

on_success:
  - ps: .\tools\publish-site.ps1
  - ps: .\tools\gh-pages.ps1 -action publish -env appveyor

environment:
  GH_TOKEN:
    secure: d3hIUMAqM1dTwnury5PzdZ/yrinP7QRmv4Uqx82i8RYLlwJV+L3gaUTaislQPmhb
  NG_TOKEN:
    secure: FQfgTTROXcWRfd//dejttogCD9EjQzBnzGYwY2Jf15X9YqJ9g5aYMwG8q9GIursS
